### ISSUE TITLE
Link to Subversion r325781 and/or Git 0271df5?

### ISSUE THREAD

**Issue by grahamperrin** [koitsu/fortune-mod-freebsd-classic#2]
Hi

https://github.com/koitsu/fortune-mod-freebsd-classic/commit/58ee9c5e4606f6ab0bf33f68213961ac3803d386#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R7

> prior to their removal in r325781 / git 0271df5.

Would you like to add a link? To <https://cgit.freebsd.org/src/commit/?id=fa193c587edc5ae8965643e290794332ed2c1430> (for `r325781`).

**Comment by grahamperrin** [comment]
### Background

Please note, this is **not** intended to condone, or promote, offensive content. 

Technically: I was curious about the **timeline** of removals (not that `0271df5` alone), and I **could not find the commit** in cgit. 

Eventually, for `0271df5` I found, archived in GitHub: 

https://github.com/freebsd/freebsd-legacy/commit/0271df5714d9ce5274f82889febb6536a2fdba59

`r325095` was mentioned alongside `r325781` in <https://lists.freebsd.org/pipermail/freebsd-hackers/2017-November/051743.html>, I became curious about the earlier of the two. 

For myself, a shortlist of four commits, the first two of which I found before browsing this repo: 

* https://cgit.freebsd.org/src/commit/?id=d886030b8a9adc87d97d42a9b686b62fcf283a1a (2011-02-13)
* https://cgit.freebsd.org/src/commit/?id=eaa2cf40226eaaa38d1f3640df4a1c8c21d20fb3 (2013-03-12)
* https://cgit.freebsd.org/src/commit/?id=417bdb60cac586a7951544cc819011e92d9a0220 (2017-10-29)
* https://cgit.freebsd.org/src/commit/?id=fa193c587edc5ae8965643e290794332ed2c1430 (2017-11-13)

– respectively, in GitHub: 

https://github.com/freebsd/freebsd-src/commit/d886030b8a9adc87d97d42a9b686b62fcf283a1a

https://github.com/freebsd/freebsd-src/commit/eaa2cf40226eaaa38d1f3640df4a1c8c21d20fb3

https://github.com/freebsd/freebsd-src/commit/417bdb60cac586a7951544cc819011e92d9a0220

https://github.com/freebsd/freebsd-src/commit/fa193c587edc5ae8965643e290794332ed2c1430

**Comment by koitsu** [comment]
> Hi
> 
> [58ee9c5#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R7](https://github.com/koitsu/fortune-mod-freebsd-classic/commit/58ee9c5e4606f6ab0bf33f68213961ac3803d386#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R7)
> 
> > prior to their removal in r325781 / git 0271df5.
> 
> Would you like to add a link? To https://cgit.freebsd.org/src/commit/?id=fa193c587edc5ae8965643e290794332ed2c1430 (for `r325781`).

The link is actually in the History section of the README.md in this repo.  I will update the README.md to turn that text string into an anchor link to the History section.

**Comment by koitsu** [comment]
I've updated README.md to reflect things a little better, including adding your mention of r218650 from 2011.  Thank you!

Some of the commits you reference in this Issue, such as r325095 / 417bdb60, are not really relevant to what this package is about.  r325095 was just HTTP -> HTTPS scheme updates for some URLs in some files (including fortunes), which is/was a completely neutral action.

I do not particularly care to deal with whatever FreeBSD has done to make a further mess of the SVN-to-Git migration (re: creation of the freebsd-legacy repository).  Until the links (to the main freebsd repo in GitHub) stop working (which would indicate someone has nuked or rewritten Git history entirely, which is awful!), I'll continue to use links that point to the "non-legacy" repo.  Also for further edification: the reason I reference both SVN revisions as well as Git commit hashes is because older commits done during the Subversion days only refer to revisions; it's so younger project contributors, who are often are unfamiliar with "the older ways" (including going back to old CVS-based commits!), have a "mapping" of both.

Again, thanks for the ticket!

**Comment by grahamperrin** [comment]
> in the History section

Oops! Sorry/thanks!

> continue to use links that point to the "non-legacy" repo. 

+1

The freebsd-legacy repo was relevant to me only as a stepping stone, and (embarrassingly) would have needed no stepping stone if I had bothered to scroll down in the README. My bad.
